# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6592ac3a3ed36b95d1bbbcf1f6b8cc4f25f4afd1ab638c086b8c9c46b66baee5095db7e7608f7763f58efedb18b7f1260ca2fecae21221ffa2fd3d767e66e9d

test:
  secret_key_base: f19b59426ff80eeafc484b46d56c1136d6b53442fb765e1663324dd732a96be45ff142e1d61209e6282b7e234c9bfb9fc94e110eebeab28855c3958be5415339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
